---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cosmic-laptop

# description will be included in the image's metadata
description: Customized Fedora COSMIC Atomic

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 43

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: rootfs
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - jsbillings/netbird
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc

    install:
      packages:
        - alacritty
        - chezmoi
        - code
        - fastfetch
        - fish
        - git-filter-repo
        - mbuffer
        - micro
        - netbird-client
        - netbird-ui
        - numix-icon-theme-circle
        - pv
        - rbw

    group-install:
      with-optional: true
      packages:
        - cosmic-desktop
        - cosmic-desktop-apps

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - thunderbird

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          title: Flathub (system)
        install:
          - com.bitwarden.desktop
          - com.brave.Browser
          - com.github.tchx84.Flatseal
          - com.mattermost.Desktop
          - com.spotify.Client
          - dev.edfloreshz.CosmicTweaks
          - io.kopia.KopiaUI
          - net.cozic.joplin_desktop
          - org.fedoraproject.MediaWriter
          - org.gnome.Loupe
          - org.localsend.localsend_app
          - us.zoom.Zoom

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - SourceCodePro

  - type: script
    snippets: []
    scripts:
      - manage_files.sh

  - type: signing

  - type: brew
    nofile-limits: true
    brew-analytics: false
    auto-upgrade: false
